name: Build and Deploy to Render

on:
  push:
    branches:
      - main
    paths:
      - '../Hackathon-KipperDev2024/apps/api/Gaia/Gaia.API'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: Login to Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6.5.0
      with:
        context: Gaia.API/
        file: Gaia.API/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Install Render CLI
      run: |
        curl -fsSL https://render.com/static/cli/render-cli-install.sh | bash

    - name: Login to Render
      run: render login --api-key ${{ secrets.RENDER_TOKEN }}

    - name: Deploy to Render
      run: render deploy service my-service-id --from-image ${{ secrets.DOCKER_USERNAME }}/my-app:latest
